export interface SportsCard {
  id: number;
  name: string;
  player: string;
  team: string;
  year: number;
  brand: string;
  set: string;
  cardNumber: string;
  condition: 'Mint' | 'Near Mint' | 'Excellent' | 'Very Good' | 'Good' | 'Fair' | 'Poor';
  price: number;
  description: string;
  imageUrl?: string;
  isSold: boolean;
}

export const mockCards: SportsCard[] = [
  {
    id: 1,
    name: "Michael Jordan Rookie Card",
    player: "Michael Jordan",
    team: "Chicago Bulls",
    year: 1986,
    brand: "Fleer",
    set: "Fleer Basketball",
    cardNumber: "57",
    condition: "Near Mint",
    price: 2500.00,
    description: "The most iconic basketball card of all time. This 1986 Fleer Michael Jordan rookie card is in excellent condition with sharp corners and vibrant colors.",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 2,
    name: "Ken Griffey Jr. Rookie",
    player: "Ken Griffey Jr.",
    team: "Seattle Mariners",
    year: 1989,
    brand: "Upper Deck",
    set: "Upper Deck Baseball",
    cardNumber: "1",
    condition: "Mint",
    price: 450.00,
    description: "The Kid's iconic Upper Deck rookie card. One of the most sought-after baseball cards from the 90s.",
    imageUrl: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 3,
    name: "Barry Sanders Rookie",
    player: "Barry Sanders",
    team: "Detroit Lions",
    year: 1989,
    brand: "Topps",
    set: "Topps Football",
    cardNumber: "62",
    condition: "Excellent",
    price: 125.00,
    description: "The elusive running back's rookie card. Known for his incredible agility and rushing yards.",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 4,
    name: "Shaquille O'Neal Rookie",
    player: "Shaquille O'Neal",
    team: "Orlando Magic",
    year: 1992,
    brand: "Topps",
    set: "Topps Basketball",
    cardNumber: "362",
    condition: "Near Mint",
    price: 85.00,
    description: "The Big Diesel's rookie card from his Orlando Magic days. A dominant force in the paint.",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 5,
    name: "Derek Jeter Rookie",
    player: "Derek Jeter",
    team: "New York Yankees",
    year: 1996,
    brand: "Topps",
    set: "Topps Baseball",
    cardNumber: "218",
    condition: "Mint",
    price: 180.00,
    description: "The Captain's rookie card. Future Hall of Famer and Yankees legend.",
    imageUrl: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 6,
    name: "Tiger Woods Rookie",
    player: "Tiger Woods",
    team: "PGA Tour",
    year: 1996,
    brand: "Upper Deck",
    set: "Upper Deck Golf",
    cardNumber: "1",
    condition: "Near Mint",
    price: 320.00,
    description: "The golfing legend's rookie card. One of the most influential athletes of all time.",
    imageUrl: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 7,
    name: "Kobe Bryant Rookie",
    player: "Kobe Bryant",
    team: "Los Angeles Lakers",
    year: 1996,
    brand: "Topps",
    set: "Topps Basketball",
    cardNumber: "138",
    condition: "Excellent",
    price: 95.00,
    description: "The Black Mamba's rookie card. A future Hall of Famer and Lakers legend.",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 8,
    name: "Peyton Manning Rookie",
    player: "Peyton Manning",
    team: "Indianapolis Colts",
    year: 1998,
    brand: "Topps",
    set: "Topps Football",
    cardNumber: "350",
    condition: "Near Mint",
    price: 75.00,
    description: "The Sheriff's rookie card. One of the greatest quarterbacks in NFL history.",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 9,
    name: "Tim Duncan Rookie",
    player: "Tim Duncan",
    team: "San Antonio Spurs",
    year: 1997,
    brand: "Topps",
    set: "Topps Basketball",
    cardNumber: "115",
    condition: "Mint",
    price: 65.00,
    description: "The Big Fundamental's rookie card. A dominant power forward and Spurs legend.",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 10,
    name: "Chipper Jones Rookie",
    player: "Chipper Jones",
    team: "Atlanta Braves",
    year: 1991,
    brand: "Topps",
    set: "Topps Baseball",
    cardNumber: "333",
    condition: "Very Good",
    price: 45.00,
    description: "The switch-hitting third baseman's rookie card. Braves legend and Hall of Famer.",
    imageUrl: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 11,
    name: "Brett Favre Rookie",
    player: "Brett Favre",
    team: "Atlanta Falcons",
    year: 1991,
    brand: "Topps",
    set: "Topps Football",
    cardNumber: "347",
    condition: "Good",
    price: 35.00,
    description: "The Gunslinger's rookie card. Known for his durability and gunslinging style.",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 12,
    name: "Allen Iverson Rookie",
    player: "Allen Iverson",
    team: "Philadelphia 76ers",
    year: 1996,
    brand: "Topps",
    set: "Topps Basketball",
    cardNumber: "237",
    condition: "Near Mint",
    price: 55.00,
    description: "The Answer's rookie card. A cultural icon and scoring machine.",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 13,
    name: "Randy Moss Rookie",
    player: "Randy Moss",
    team: "Minnesota Vikings",
    year: 1998,
    brand: "Topps",
    set: "Topps Football",
    cardNumber: "351",
    condition: "Excellent",
    price: 40.00,
    description: "The Freak's rookie card. One of the most talented wide receivers ever.",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 14,
    name: "Vince Carter Rookie",
    player: "Vince Carter",
    team: "Toronto Raptors",
    year: 1998,
    brand: "Topps",
    set: "Topps Basketball",
    cardNumber: "123",
    condition: "Mint",
    price: 30.00,
    description: "Half Man, Half Amazing's rookie card. Known for his incredible dunks.",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 15,
    name: "Tom Brady Rookie",
    player: "Tom Brady",
    team: "New England Patriots",
    year: 2000,
    brand: "Topps",
    set: "Topps Football",
    cardNumber: "236",
    condition: "Near Mint",
    price: 15.00,
    description: "The GOAT's rookie card. The greatest quarterback of all time.",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 16,
    name: "LeBron James Rookie",
    player: "LeBron James",
    team: "Cleveland Cavaliers",
    year: 2003,
    brand: "Topps",
    set: "Topps Basketball",
    cardNumber: "221",
    condition: "Mint",
    price: 8.00,
    description: "The King's rookie card. One of the greatest basketball players ever.",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 17,
    name: "Derek Jeter Base Card",
    player: "Derek Jeter",
    team: "New York Yankees",
    year: 1998,
    brand: "Topps",
    set: "Topps Baseball",
    cardNumber: "42",
    condition: "Very Good",
    price: 12.00,
    description: "Classic Jeter base card from his prime years with the Yankees.",
    imageUrl: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 18,
    name: "Michael Jordan Base Card",
    player: "Michael Jordan",
    team: "Chicago Bulls",
    year: 1992,
    brand: "Upper Deck",
    set: "Upper Deck Basketball",
    cardNumber: "23",
    condition: "Excellent",
    price: 25.00,
    description: "Classic MJ base card from his championship years with the Bulls.",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 19,
    name: "Ken Griffey Jr. Base Card",
    player: "Ken Griffey Jr.",
    team: "Seattle Mariners",
    year: 1993,
    brand: "Topps",
    set: "Topps Baseball",
    cardNumber: "405",
    condition: "Good",
    price: 8.00,
    description: "Classic Griffey base card from his Mariners days.",
    imageUrl: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400&h=600&fit=crop",
    isSold: false
  },
  {
    id: 20,
    name: "Barry Sanders Base Card",
    player: "Barry Sanders",
    team: "Detroit Lions",
    year: 1995,
    brand: "Topps",
    set: "Topps Football",
    cardNumber: "78",
    condition: "Very Good",
    price: 15.00,
    description: "Classic Sanders base card from his prime years with the Lions.",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop",
    isSold: false
  }
];
